// ============================================
// THE PATH TO PEACE — All Data
// ============================================

// ---- Cause Categories (Overview) ----
const causeCategories = [
  { icon: '⛽', title: 'Resources & Territory', desc: 'Oil, water, minerals, land, and strategic access points', color: '#e67e22' },
  { icon: '👑', title: 'Power & Governance', desc: 'Authoritarian control, failed states, coups, and political exclusion', color: '#e74c3c' },
  { icon: '🕊️', title: 'Identity & Religion', desc: 'Ethnic tensions, sectarian divides, and cultural suppression', color: '#9b59b6' },
  { icon: '🏛️', title: 'Colonial Legacy', desc: 'Arbitrary borders, unresolved grievances, and institutional fractures', color: '#3498db' },
  { icon: '☢️', title: 'Nuclear & Arms', desc: 'Weapons proliferation, deterrence failures, and arms races', color: '#f1c40f' },
  { icon: '💰', title: 'Economic Inequality', desc: 'Poverty, corruption, resource extraction, and exploitation', color: '#1abc9c' },
  { icon: '🌍', title: 'Geopolitical Rivalry', desc: 'Great power competition, proxy wars, and spheres of influence', color: '#2ecc71' },
  { icon: '🌡️', title: 'Climate & Scarcity', desc: 'Drought, displacement, food insecurity driving instability', color: '#e74c3c' },
];

// ---- Current Conflicts ----
const currentConflicts = [
  {
    id: 'russia-ukraine',
    name: 'Russia–Ukraine War',
    region: 'Eastern Europe',
    type: 'war',
    severity: 'critical',
    started: 'February 2022 (roots in 2014)',
    displaced: '~14 million',
    casualties: '500,000+ military casualties (estimated)',
    summary: 'Russia\'s full-scale invasion of Ukraine — the largest land war in Europe since 1945. A fight over sovereignty, NATO expansion, and the post-Cold War order.',
    causes: ['Territory', 'Geopolitics', 'Identity', 'Security'],
    who: {
      sideA: 'Russian Federation (with allied forces from Belarus, and recruited fighters)',
      sideB: 'Ukraine (supported by NATO allies, EU military and financial aid)',
    },
    why: 'Russia views Ukraine\'s westward orientation and potential NATO membership as an existential threat to its security and sphere of influence. Ukraine asserts its sovereign right to choose its own alliances and future. Deeper roots include post-Soviet identity disputes, the status of Crimea (annexed by Russia in 2014), and the conflict in the Donbas region since 2014.',
    resources: 'Ukraine holds significant agricultural land (one of the world\'s top grain exporters), energy transit pipelines, and mineral deposits including lithium and rare earths. Control of the Black Sea and Crimea provides strategic naval access.',
    whatAbout: 'Sovereignty and territorial integrity vs. claimed security interests; the post-Cold War European security architecture; the right of nations to choose their own alliances; Russian-speaking populations in eastern Ukraine; energy politics and gas pipelines to Europe.',
    pathToResolution: 'Ceasefire negotiations, security guarantees for both sides, territorial status discussions, reconstruction plans, accountability mechanisms, and a new European security framework. Historical parallels include the Helsinki Accords and post-WWII settlement.',
    impact: 'Global food price spikes, European energy crisis, nuclear escalation fears, millions displaced, massive infrastructure destruction, and a fundamental reshaping of European security.',
  },
  {
    id: 'israel-palestine',
    name: 'Israel–Palestine Conflict',
    region: 'Middle East',
    type: 'war',
    severity: 'critical',
    started: 'October 2023 escalation (roots in 1948)',
    displaced: '~2.3 million in Gaza',
    casualties: 'Tens of thousands killed in Gaza; 1,200+ killed in Israel on Oct. 7',
    summary: 'One of the world\'s longest-running conflicts, dramatically escalated after the October 7, 2023 Hamas attack and Israel\'s subsequent military campaign in Gaza.',
    causes: ['Territory', 'Identity', 'Self-determination', 'Security'],
    who: {
      sideA: 'State of Israel (supported by the United States and Western allies)',
      sideB: 'Hamas (governing Gaza since 2007), Palestinian civilians, broader Palestinian national movement',
    },
    why: 'Rooted in competing national claims to the same land. The 1948 establishment of Israel led to Palestinian displacement (the Nakba). Decades of occupation, settlement expansion, blockades, and failed peace processes have created cycles of violence. The October 7 attack and subsequent military response represent a catastrophic escalation of these unresolved tensions.',
    resources: 'Control of land, water aquifers, and offshore gas fields. Jerusalem holds immense religious significance for Judaism, Islam, and Christianity. Strategic location at the crossroads of three continents.',
    whatAbout: 'Palestinian statehood and self-determination; Israeli security; the status of Jerusalem; refugee right of return; settlement expansion in the West Bank; the blockade of Gaza; international law and human rights; the two-state solution vs. alternatives.',
    pathToResolution: 'Immediate ceasefire and humanitarian access, hostage/prisoner negotiations, addressing root causes through a political framework that guarantees both Israeli security and Palestinian self-determination. Historical models include the Oslo process and the Good Friday Agreement\'s approach to shared sovereignty.',
    impact: 'Massive humanitarian crisis in Gaza, regional destabilization (Hezbollah, Houthis), global protest movements, deep polarization, and challenges to international law frameworks.',
  },
  {
    id: 'sudan',
    name: 'Sudan Civil War',
    region: 'East Africa',
    type: 'civil-war',
    severity: 'critical',
    started: 'April 2023',
    displaced: '~10 million',
    casualties: '15,000+ killed (likely far higher)',
    summary: 'A power struggle between two military factions has plunged Sudan into one of the world\'s worst humanitarian catastrophes, with famine, mass displacement, and widespread atrocities.',
    causes: ['Power', 'Resources', 'Ethnic tensions', 'Colonial legacy'],
    who: {
      sideA: 'Sudanese Armed Forces (SAF) led by Gen. Abdel Fattah al-Burhan',
      sideB: 'Rapid Support Forces (RSF) led by Gen. Mohamed Hamdan "Hemedti" Dagalo',
    },
    why: 'After the 2019 revolution that ousted dictator Omar al-Bashir, a fragile military-civilian transition collapsed. The two most powerful military leaders — who had jointly staged a coup in 2021 — turned on each other in a fight for control of the state and its vast resources, including gold mines. The RSF evolved from the Janjaweed militias responsible for atrocities in Darfur.',
    resources: 'Gold (Sudan is Africa\'s third-largest producer), agricultural land along the Nile, strategic Red Sea coast access, and oil. Control of these resources funds both warring parties.',
    whatAbout: 'Control of the state; distribution of economic resources (especially gold); the future of democratic transition; ethnic and regional marginalization; accountability for past atrocities in Darfur; foreign interference from UAE, Egypt, Russia, and others.',
    pathToResolution: 'Ceasefire enforcement, civilian protection, humanitarian access, inclusive political dialogue that includes civilian pro-democracy movements, arms embargo enforcement, and accountability for war crimes. The 2005 Comprehensive Peace Agreement (which led to South Sudan\'s independence) offers partial precedent.',
    impact: 'World\'s largest displacement crisis, famine conditions, ethnic cleansing in Darfur, collapse of health and education systems, and regional refugee spillover.',
  },
  {
    id: 'myanmar',
    name: 'Myanmar Civil War',
    region: 'Southeast Asia',
    type: 'civil-war',
    severity: 'high',
    started: 'February 2021 (ethnic conflicts since independence)',
    displaced: '~3 million',
    casualties: 'Tens of thousands killed',
    summary: 'Following the 2021 military coup that overthrew the elected government, a nationwide resistance movement has escalated into full civil war, with ethnic armed organizations joining the fight against the junta.',
    causes: ['Power', 'Ethnic rights', 'Democracy', 'Colonial legacy'],
    who: {
      sideA: 'Myanmar military junta (Tatmadaw) led by Gen. Min Aung Hlaing',
      sideB: 'National Unity Government (NUG), People\'s Defense Forces (PDF), and numerous ethnic armed organizations (EAOs) including Kachin, Karen, Chin, Shan, and Arakan armies',
    },
    why: 'The military seized power to prevent a democratic transition that threatened its political and economic dominance. Deeper roots include decades of ethnic persecution (including the Rohingya genocide), military rule since 1962, and a constitution designed to guarantee military power. The resistance unites pro-democracy movements with long-standing ethnic autonomy struggles.',
    resources: 'Jade and gemstones (Myanmar produces 90% of the world\'s jade), timber, natural gas, rare earth minerals. The military controls vast business empires through crony networks.',
    whatAbout: 'Democracy vs. military rule; ethnic self-determination and federalism; the Rohingya crisis; military economic empire; drug production in the Golden Triangle; China\'s strategic interests.',
    pathToResolution: 'The resistance aims for a federal democratic union. International pressure through sanctions, arms embargo, and diplomatic isolation of the junta. ASEAN\'s Five-Point Consensus has been ineffective. South Africa\'s transition from apartheid through negotiated settlement offers one model.',
    impact: 'Humanitarian crisis, collapse of healthcare and education, narcotics production surge, regional instability, and a test case for whether democratic movements can prevail against entrenched military power.',
  },
  {
    id: 'ethiopia',
    name: 'Ethiopia: Post-Tigray & Ongoing Conflicts',
    region: 'East Africa / Horn of Africa',
    type: 'civil-war',
    severity: 'high',
    started: 'November 2020 (Tigray); ongoing conflicts in Amhara, Oromia',
    displaced: '~4.5 million internally',
    casualties: '600,000+ estimated deaths in Tigray war',
    summary: 'While the devastating Tigray war ended with a 2022 ceasefire, Ethiopia faces ongoing armed conflicts in the Amhara and Oromia regions, threatening the country\'s unity and stability.',
    causes: ['Ethnic federalism', 'Power', 'Land', 'Identity'],
    who: {
      sideA: 'Ethiopian federal government under PM Abiy Ahmed (with Eritrean alliance)',
      sideB: 'Various: Tigray People\'s Liberation Front (TPLF), Fano militias in Amhara, Oromo Liberation Army (OLA)',
    },
    why: 'Ethiopia\'s ethnic federal system, designed to manage diversity, has also entrenched ethnic identity as the primary political currency. PM Abiy\'s centralization efforts alienated multiple ethnic groups. The Tigray war was one of the deadliest conflicts of the 21st century. Now, former allies (Amhara Fano militias) have turned against the government, and the Oromo insurgency continues.',
    resources: 'Agricultural land in one of Africa\'s most fertile regions, the Grand Ethiopian Renaissance Dam (control over Nile waters, disputed with Egypt and Sudan), minerals, and strategic Horn of Africa location.',
    whatAbout: 'Ethnic self-determination vs. national unity; the future of ethnic federalism; land rights and displacement; Nile water access (GERD dispute); accountability for atrocities; Eritrea\'s role.',
    pathToResolution: 'Implementation of the Pretoria Agreement (Tigray ceasefire), inclusive national dialogue, reform of the ethnic federal system, transitional justice mechanisms, and addressing root causes of marginalization. The Pretoria process itself offers a recent success model.',
    impact: 'One of the deadliest conflicts of the 2020s, massive displacement, famine, destruction of Tigray\'s infrastructure, and regional destabilization.',
  },
  {
    id: 'yemen',
    name: 'Yemen Civil War',
    region: 'Middle East / Arabian Peninsula',
    type: 'civil-war',
    severity: 'high',
    started: '2014 (intensified 2015)',
    displaced: '~4.5 million',
    casualties: '377,000+ deaths (including from famine and disease)',
    summary: 'A devastating civil war fueled by regional rivalries between Saudi Arabia and Iran, creating what the UN called the world\'s worst humanitarian crisis.',
    causes: ['Power', 'Sectarian', 'Geopolitics', 'Resources'],
    who: {
      sideA: 'Ansar Allah (Houthi movement), backed by Iran',
      sideB: 'Internationally recognized government, backed by Saudi-led coalition (including UAE)',
    },
    why: 'Houthi insurgents from the Zaidi Shia north captured the capital Sana\'a, overthrowing the transitional government. Saudi Arabia intervened militarily in 2015, framing the conflict as a proxy war against Iranian influence. Underlying causes include decades of north-south division, economic marginalization, corruption, and the failed political transition after the 2011 Arab Spring.',
    resources: 'Modest oil and gas reserves, but strategic control of the Bab el-Mandeb strait (one of the world\'s most important shipping lanes). The Houthi Red Sea attacks since 2023 demonstrate this strategic leverage.',
    whatAbout: 'Control of the Yemeni state; Saudi-Iran regional rivalry; Zaidi Shia identity and marginalization; the southern independence movement; control of shipping lanes; the war economy and fragmentation of armed groups.',
    pathToResolution: 'UN-mediated peace process, Saudi-Houthi direct negotiations (ongoing), power-sharing arrangement, unified security forces, reconstruction, and addressing the humanitarian crisis. The 2023 Saudi-Iran rapprochement (brokered by China) opened new diplomatic space.',
    impact: 'Catastrophic humanitarian crisis with famine, cholera epidemics, destruction of infrastructure, a generation of children out of school, and global shipping disruption.',
  },
  {
    id: 'drc',
    name: 'DR Congo: Eastern Conflict',
    region: 'Central Africa',
    type: 'civil-war',
    severity: 'high',
    started: '1996 (current phase since 2021)',
    displaced: '~7 million internally',
    casualties: 'Millions over decades (deadliest conflict since WWII)',
    summary: 'The resource-rich eastern Congo remains devastated by over 100 armed groups fighting for control of minerals, land, and power — with significant involvement from neighboring Rwanda and Uganda.',
    causes: ['Resources', 'Ethnic tensions', 'Colonial legacy', 'Geopolitics'],
    who: {
      sideA: 'Congolese armed forces (FARDC), various Mai-Mai militias',
      sideB: 'M23 rebels (backed by Rwanda), Allied Democratic Forces (ADF), 100+ other armed groups',
    },
    why: 'Eastern DRC holds enormous mineral wealth (coltan, cobalt, gold, cassiterite) that fuels armed groups and attracts foreign interference. The roots trace to the 1994 Rwandan genocide, when Hutu perpetrators fled into Congo, triggering two continental wars. Weak state presence, ethnic land disputes, and exploitation by neighboring powers perpetuate the cycle.',
    resources: 'Coltan (essential for electronics), cobalt (critical for batteries/EVs), gold, diamonds, timber, and cassiterite. Eastern DRC supplies minerals critical to global technology supply chains.',
    whatAbout: 'Control of mineral wealth; Rwanda\'s security concerns and economic interests; ethnic Tutsi/Hutu dynamics spilling across borders; state weakness and corruption; the global supply chain\'s role in fueling conflict; UN peacekeeping failures.',
    pathToResolution: 'Enforcement of mineral traceability and due diligence, regional diplomatic engagement (Luanda and Nairobi processes), security sector reform, extension of state authority to the east, accountability for Rwanda\'s role, and community-level reconciliation. Conflict mineral legislation (like the EU\'s) shows how consumer countries can help.',
    impact: 'The deadliest conflict since WWII in cumulative toll, massive sexual violence used as a weapon of war, child soldier recruitment, displacement, and global ethical questions about mineral supply chains.',
  },
  {
    id: 'sahel',
    name: 'Sahel Crisis (Mali, Burkina Faso, Niger)',
    region: 'West Africa',
    type: 'insurgency',
    severity: 'high',
    started: '2012 (Mali); expanded regionally',
    displaced: '~3.8 million',
    casualties: 'Tens of thousands',
    summary: 'Jihadist insurgencies, military coups, and intercommunal violence have destabilized the entire Sahel region, with governments turning to Russia\'s Wagner Group after expelling French forces.',
    causes: ['Governance failure', 'Extremism', 'Colonial legacy', 'Climate'],
    who: {
      sideA: 'Military juntas (Mali, Burkina Faso, Niger — Alliance of Sahel States), Wagner Group/Africa Corps',
      sideB: 'Jihadist groups (JNIM linked to al-Qaeda, Islamic State Sahel Province), also some Tuareg separatists',
    },
    why: 'State weakness, corruption, and neglect of peripheral regions created a governance vacuum. The 2011 collapse of Libya flooded the region with weapons. Jihadist groups exploited local grievances — ethnic marginalization, land disputes, lack of services — to recruit fighters. French military intervention (2013-2022) failed to address root causes. Military coups promised security but haven\'t delivered.',
    resources: 'Gold (Mali and Burkina Faso are significant producers), uranium (Niger supplies ~5% of global production), pastoral land increasingly scarce due to climate change, and narcotics trafficking routes.',
    whatAbout: 'State failure and military governance; jihadist expansion; climate-driven farmer-herder conflicts; French neo-colonial legacy; Russia\'s expanding influence in Africa; the future of ECOWAS; civilian protection; youth radicalization driven by poverty and exclusion.',
    pathToResolution: 'Governance reform that delivers services and justice to rural populations, addressing climate-driven resource competition, community-based conflict resolution between farmers and herders, deradicalization programs, and regional cooperation. Local peace agreements in Mali show promise.',
    impact: 'Spreading instability threatening West African coast countries, democratic backsliding, humanitarian crisis, and a test case for competing Russian and Western influence in Africa.',
  },
  {
    id: 'syria',
    name: 'Syria: Post-Assad Transition',
    region: 'Middle East',
    type: 'civil-war',
    severity: 'medium',
    started: '2011 (new phase since Assad\'s fall in late 2024)',
    displaced: '~12 million (half the pre-war population)',
    casualties: '500,000+ killed since 2011',
    summary: 'After 13 years of devastating civil war, the Assad regime fell in late 2024. Syria now faces the immense challenge of transition, reconstruction, and reconciliation amid ongoing fragmentation.',
    causes: ['Authoritarian rule', 'Sectarian', 'Geopolitics', 'Resources'],
    who: {
      sideA: 'New transitional authorities (HTS-led)',
      sideB: 'Various: remaining regime loyalists, ISIS remnants, Kurdish autonomous forces (SDF), Turkish-backed factions',
    },
    why: 'The 2011 Arab Spring uprising against the Assad dynasty was met with extreme military repression, spiraling into civil war. International involvement from Russia, Iran, Turkey, the US, and Gulf states turned Syria into a proxy battlefield. The war produced one of the century\'s worst refugee crises. Assad\'s fall opens possibilities but also risks further fragmentation.',
    resources: 'Oil and gas reserves (modest but contested), agricultural land, water resources (Euphrates), and strategic location connecting the Mediterranean to the Middle East.',
    whatAbout: 'Building a new inclusive government; Kurdish autonomy; ISIS remnants; refugee return; reconstruction (estimated $400B+); Turkish security concerns; Iran and Russia\'s diminished influence; transitional justice for war crimes; de-mining; rebuilding shattered institutions.',
    pathToResolution: 'Inclusive political transition under UN framework (Resolution 2254), constitutional reform, security sector integration, refugee return facilitation, massive reconstruction effort, and transitional justice. Post-WWII Germany and post-Dayton Bosnia offer models for reconstruction and reconciliation.',
    impact: 'Largest refugee crisis of the 21st century, shaped the global migration debate, demonstrated limits of humanitarian intervention, and reshaped Middle Eastern geopolitics.',
  },
  {
    id: 'haiti',
    name: 'Haiti: Gang Violence & State Collapse',
    region: 'Caribbean / Americas',
    type: 'civil-war',
    severity: 'high',
    started: '2021 (escalated), decades of instability',
    displaced: '~700,000 internally',
    casualties: 'Thousands killed annually',
    summary: 'Haiti faces near-complete state collapse as armed gangs control most of the capital Port-au-Prince and expand nationwide, creating a catastrophic humanitarian emergency.',
    causes: ['Governance failure', 'Poverty', 'Colonial legacy', 'Foreign interference'],
    who: {
      sideA: 'Haitian National Police (severely under-resourced), Kenyan-led Multinational Security Support mission',
      sideB: 'Armed gang coalitions (G9, G-Pèp), with ties to political and economic elites',
    },
    why: 'Haiti\'s crisis stems from centuries of exploitation — from slavery and French colonial extraction (Haiti was forced to pay "independence debt" until 1947), to repeated US interventions, to decades of corrupt governance and international neglect. The 2021 assassination of President Moïse created a complete power vacuum. Gangs, originally armed by political elites, now control most territory.',
    resources: 'Limited natural resources (largely deforested), but control of ports, customs revenue, and drug trafficking routes. Haiti\'s poverty itself is a resource issue — the result of systematic extraction dating to colonial times.',
    whatAbout: 'State rebuilding from near-zero; gang disarmament and reintegration; restoring basic services (healthcare, education, water); addressing extreme poverty and inequality; the legacy of colonialism and foreign debt; democratic governance; security force reform.',
    pathToResolution: 'Security stabilization (MSS mission), gang disruption combined with community reintegration programs, transitional governance leading to elections, massive investment in basic services, and addressing the root economic causes. Colombia\'s demobilization process and Sierra Leone\'s recovery offer relevant models.',
    impact: 'Complete humanitarian catastrophe in the Western hemisphere, mass migration, challenge to regional stability, and a stark example of how colonial legacies compound over centuries.',
  },
  {
    id: 'south-china-sea',
    name: 'South China Sea Tensions',
    region: 'Indo-Pacific',
    type: 'tension',
    severity: 'tension',
    started: 'Escalating since 2010s',
    displaced: 'N/A (military standoffs, not active combat)',
    casualties: 'Limited (confrontations, water cannon incidents)',
    summary: 'China\'s expansive territorial claims over nearly the entire South China Sea put it in direct conflict with the Philippines, Vietnam, Taiwan, Malaysia, and Brunei — with the US backing its allies.',
    causes: ['Territory', 'Resources', 'Geopolitics', 'Trade routes'],
    who: {
      sideA: 'China (asserting "nine-dash line" claims)',
      sideB: 'Philippines, Vietnam, Taiwan, Malaysia, Brunei — backed by the United States, Japan, Australia',
    },
    why: 'China claims historical sovereignty over most of the South China Sea, building artificial islands with military installations. This clashes with international law (the 2016 Hague tribunal ruled against China\'s claims) and the sovereignty of neighboring states. The US sees free navigation as essential to the rules-based order and its Indo-Pacific alliances.',
    resources: 'Massive fisheries (12% of global catch), estimated 11 billion barrels of oil and 190 trillion cubic feet of natural gas, and $5.3 trillion in annual shipping trade passes through these waters.',
    whatAbout: 'Freedom of navigation and international law; resource rights in exclusive economic zones; China\'s rise and territorial ambitions; US-China strategic competition; ASEAN unity; risk of miscalculation leading to conflict between nuclear powers.',
    pathToResolution: 'Enforcement of UNCLOS and the 2016 arbitral ruling, a binding Code of Conduct between ASEAN and China, joint resource development agreements, military-to-military communication channels to prevent escalation, and diplomatic frameworks for peaceful dispute resolution.',
    impact: 'Risk of great power conflict, threats to global trade ($5.3T annually), militarization of international waters, stress-testing of international law.',
  },
  {
    id: 'taiwan',
    name: 'Taiwan Strait Tensions',
    region: 'East Asia / Indo-Pacific',
    type: 'tension',
    severity: 'tension',
    started: 'Since 1949 (escalating since 2020s)',
    displaced: 'N/A (no active combat)',
    casualties: 'N/A',
    summary: 'The risk of conflict over Taiwan represents the single most dangerous flashpoint for a potential great power war between the US and China, with massive global implications.',
    causes: ['Sovereignty', 'Geopolitics', 'Identity', 'Economics'],
    who: {
      sideA: 'People\'s Republic of China (claims Taiwan as part of its territory)',
      sideB: 'Taiwan (de facto independent democracy since 1949), backed by the United States under the Taiwan Relations Act',
    },
    why: 'When the Chinese Communist Party won the civil war in 1949, the defeated Nationalist government fled to Taiwan. China has never renounced the use of force to achieve "reunification." Taiwan has evolved into a vibrant democracy with its own identity and has no desire for unification. The US maintains strategic ambiguity — recognizing Beijing diplomatically while providing Taiwan with defensive arms.',
    resources: 'Taiwan produces over 90% of the world\'s most advanced semiconductors (TSMC). A conflict would devastate global technology supply chains. Taiwan Strait is also a critical shipping lane.',
    whatAbout: 'Self-determination vs. territorial claims; the semiconductor global supply chain; US-China great power rivalry; the future of democracy in Asia; nuclear deterrence; the rules-based international order.',
    pathToResolution: 'Maintaining the status quo through deterrence, economic interdependence, and diplomatic channels. Cross-strait dialogue, confidence-building measures, and multilateral frameworks for managing tensions. The Cold War model of "peaceful coexistence" while maintaining distinct systems offers one precedent.',
    impact: 'A conflict would be catastrophic: global semiconductor shortage (crippling tech, automotive, medical industries), potential nuclear escalation, disruption of $2.45T in annual trade through the strait, and a global economic depression.',
  },
  {
    id: 'north-korea',
    name: 'Korean Peninsula Nuclear Tensions',
    region: 'East Asia',
    type: 'tension',
    severity: 'tension',
    started: '1953 armistice (never formally ended); nuclear since 2006',
    displaced: 'N/A',
    casualties: 'N/A (armistice holds)',
    summary: 'North Korea\'s growing nuclear arsenal and missile capabilities represent a persistent threat to regional and global security, with the Korean War technically still unresolved after 70+ years.',
    causes: ['Nuclear weapons', 'Geopolitics', 'Ideology', 'Security'],
    who: {
      sideA: 'North Korea (DPRK) under Kim Jong Un, supported by China and increasingly Russia',
      sideB: 'South Korea (ROK) and the United States, with Japan as a key regional partner',
    },
    why: 'The Korean Peninsula was divided in 1945 and fought a devastating war (1950-53) that never formally ended. North Korea pursued nuclear weapons as a regime survival strategy, believing they are the ultimate guarantee against invasion. Diplomatic efforts (Six-Party Talks, 2018 summits) have failed to achieve denuclearization. North Korea\'s growing cooperation with Russia (providing weapons for Ukraine) has added new complexity.',
    resources: 'North Korea has significant untapped mineral resources (rare earths, coal, iron ore). The Korean Peninsula\'s strategic location between China, Japan, and Russia makes it a geopolitical pivot point.',
    whatAbout: 'Nuclear proliferation and disarmament; regime survival vs. international security; human rights in North Korea; Korean reunification; US military presence in Asia; the nuclear deterrence doctrine; sanctions effectiveness.',
    pathToResolution: 'Arms control agreements (building on past frameworks like the Agreed Framework), security guarantees in exchange for denuclearization steps, humanitarian engagement, economic incentives, and eventually a peace treaty to formally end the Korean War. The Iran nuclear deal (JCPOA) showed both the potential and fragility of nuclear agreements.',
    impact: 'Ongoing risk of nuclear conflict, humanitarian crisis inside North Korea, proliferation risk (technology and materials), and impediment to Northeast Asian economic integration.',
  },
  {
    id: 'somalia',
    name: 'Somalia: Al-Shabaab Insurgency',
    region: 'East Africa / Horn of Africa',
    type: 'insurgency',
    severity: 'medium',
    started: '2006 (Al-Shabaab); state collapse since 1991',
    displaced: '~3.8 million',
    casualties: 'Thousands annually',
    summary: 'Al-Shabaab, Africa\'s deadliest militant group, continues to wage an insurgency against the Somali federal government despite decades of international intervention.',
    causes: ['Governance failure', 'Extremism', 'Clan rivalry', 'Colonial legacy'],
    who: {
      sideA: 'Somali federal government, African Union Transition Mission (ATMIS)',
      sideB: 'Al-Shabaab (al-Qaeda affiliate), ISIS-Somalia (smaller faction)',
    },
    why: 'Somalia\'s central government collapsed in 1991, and over three decades of civil war, clan competition, and foreign intervention followed. Al-Shabaab emerged from the Islamic Courts Union and exploits governance gaps, providing crude but functional justice and services where the state cannot. The group controls significant territory in south-central Somalia.',
    resources: 'Livestock (Somalia\'s main export), charcoal trade (a major Al-Shabaab revenue source), fisheries, and modest oil/gas potential. Strategic location on the Horn of Africa and Gulf of Aden shipping lanes.',
    whatAbout: 'State-building in a fragmented society; clan-based politics; the limits of military counterterrorism; youth radicalization driven by unemployment; climate-driven displacement and food insecurity; regional dynamics (Ethiopia, Kenya, Djibouti); the African Union mission\'s future.',
    pathToResolution: 'Community-level governance strengthening, defector reintegration programs, inclusive political settlement addressing clan grievances, economic development especially for youth, and addressing climate-driven food insecurity. Local clan-based peace agreements (like the Somaliland model) have shown success.',
    impact: 'Chronic humanitarian crisis, piracy (disrupting global shipping), terrorism risk extending to Kenya and the region, and a test case for state-building after total collapse.',
  },
  {
    id: 'nagorno-karabakh',
    name: 'Armenia–Azerbaijan: Post-Karabakh Tensions',
    region: 'South Caucasus',
    type: 'tension',
    severity: 'medium',
    started: '1988-94 war; 2020 war; 2023 Azerbaijan retook Karabakh',
    displaced: '~120,000 ethnic Armenians (entire population of Karabakh)',
    casualties: '~7,000 killed in 2020 war',
    summary: 'Azerbaijan\'s 2023 military operation in Nagorno-Karabakh resulted in the flight of the entire ethnic Armenian population. Tensions now center on demarcating the Armenia-Azerbaijan border and a potential peace treaty.',
    causes: ['Territory', 'Ethnic identity', 'Soviet legacy', 'Geopolitics'],
    who: {
      sideA: 'Azerbaijan (backed by Turkey)',
      sideB: 'Armenia (historically backed by Russia, now seeking Western ties)',
    },
    why: 'Nagorno-Karabakh was an Armenian-populated enclave within Azerbaijan\'s borders, a legacy of Soviet-era administrative boundaries. Ethnic conflict erupted as the USSR collapsed. Armenia controlled the region for three decades until Azerbaijan, modernized with oil wealth and Turkish military support, recaptured it in 2020 and fully in 2023.',
    resources: 'Azerbaijan\'s oil and gas wealth funded its military modernization. Strategic pipeline and transport corridor routes through the South Caucasus are contested.',
    whatAbout: 'Ethnic cleansing and displacement; border demarcation; prisoner of war release; cultural heritage preservation; Russia\'s declining influence in its "near abroad"; Turkey\'s rising regional role; the Zangezur corridor dispute.',
    pathToResolution: 'A comprehensive peace treaty normalizing relations, clear border demarcation, resolution of remaining prisoners and displaced persons issues, and a framework for regional economic cooperation. The Dayton Accords (Bosnia) and Erdogan-Assad rapprochement offer models for post-conflict normalization.',
    impact: 'Complete ethnic displacement of Karabakh Armenians, shifting regional power dynamics, demonstration of drone warfare effectiveness, and Russia\'s weakened role as regional guarantor.',
  },
];

// ---- Root Causes Deep Dive ----
const rootCauses = [
  {
    number: '01',
    title: 'Resources & Economic Greed',
    color: '#e67e22',
    shortDesc: 'Control of oil, minerals, water, and land drives or sustains most conflicts',
    fullDesc: 'Throughout history, control of valuable resources has been one of the most persistent drivers of conflict. In the modern era, this extends beyond traditional resources like land and water to include critical minerals for technology, energy supplies, and even drug trafficking routes. Resource conflicts are particularly dangerous because they create self-sustaining war economies — armed groups fund themselves through resource extraction, making peace economically disadvantageous for those in power.',
    examples: [
      { name: 'DR Congo', detail: 'Coltan and cobalt in your phone and electric car fund armed groups' },
      { name: 'Sudan', detail: 'Gold mining revenue finances both warring factions, especially RSF' },
      { name: 'South China Sea', detail: '$5.3 trillion in annual trade and vast oil/gas reserves' },
      { name: 'Yemen', detail: 'Control of the Bab el-Mandeb strait and its global shipping leverage' },
      { name: 'Iraq (2003)', detail: 'Oil-rich nation invaded under disputed pretexts' },
    ]
  },
  {
    number: '02',
    title: 'Power, Authoritarianism & Governance Failure',
    color: '#e74c3c',
    shortDesc: 'When governments serve the few, exclude the many, or collapse entirely',
    fullDesc: 'The single biggest predictor of internal conflict is governance quality. Authoritarian regimes that concentrate power, exclude ethnic or political groups, and use violence to maintain control create the conditions for rebellion. Conversely, states that collapse — losing the monopoly on violence and the ability to provide basic services — create vacuums that armed groups fill. Democratic backsliding and coups have increased globally since the mid-2010s, reversing decades of progress.',
    examples: [
      { name: 'Myanmar', detail: 'Military coup overthrew democracy, sparking nationwide resistance' },
      { name: 'Sudan', detail: 'Two generals fighting for control of the state after blocking civilian rule' },
      { name: 'Syria', detail: '13 years of war began when Assad responded to protests with military force' },
      { name: 'Haiti', detail: 'Complete state collapse, gangs filling the governance vacuum' },
      { name: 'Sahel', detail: 'Military coups in Mali, Burkina Faso, Niger — promising but not delivering security' },
    ]
  },
  {
    number: '03',
    title: 'Identity, Ethnicity & Religion',
    color: '#9b59b6',
    shortDesc: 'When identity becomes politicized and used to divide, dehumanize, and mobilize',
    fullDesc: 'Identity conflicts are rarely about identity alone — they are about power, access, and belonging. When political leaders weaponize ethnic or religious differences to gain or maintain power, they create deep social fractures. Dehumanization of an "other" group is a consistent precursor to mass atrocities. However, diverse societies can be remarkably peaceful when governance is inclusive. The key variable is not diversity itself but whether political systems manage diversity through inclusion or exploitation.',
    examples: [
      { name: 'Israel-Palestine', detail: 'Competing national identities and claims to the same land' },
      { name: 'Ethiopia', detail: 'Ethnic federalism turned identity into the primary political currency' },
      { name: 'Myanmar', detail: 'Rohingya genocide — ethnic persecution as state policy' },
      { name: 'Balkans (1990s)', detail: 'Ethnic mobilization tore apart a multiethnic state' },
      { name: 'Rwanda (1994)', detail: 'Hutu-Tutsi divisions manipulated into genocide' },
    ]
  },
  {
    number: '04',
    title: 'Colonial Legacy & Historical Grievance',
    color: '#3498db',
    shortDesc: 'Borders drawn by colonizers, institutions designed for extraction, and debts of injustice',
    fullDesc: 'The borders of most countries in Africa, the Middle East, and parts of Asia were drawn by European colonial powers with little regard for ethnic, linguistic, or cultural realities. This created states with built-in tensions — different groups forced together, or single groups divided across borders. Colonial economic systems designed for extraction rather than development left institutional weakness. And the psychological and economic damage of colonialism — including forced debt, as in Haiti\'s case — creates grievances that compound over generations.',
    examples: [
      { name: 'DRC', detail: 'Belgian colonial brutality left institutional weakness exploited for decades' },
      { name: 'Haiti', detail: 'Forced to pay France $21 billion (modern value) for its own freedom' },
      { name: 'Israel-Palestine', detail: 'British Mandate-era promises to both Jews and Arabs' },
      { name: 'Sahel', detail: 'French colonial boundaries and post-colonial economic extraction' },
      { name: 'Myanmar', detail: 'British divide-and-rule policies entrenched ethnic hierarchies' },
    ]
  },
  {
    number: '05',
    title: 'Nuclear Weapons & Arms Proliferation',
    color: '#f1c40f',
    shortDesc: 'Weapons that can end civilization, and the arms trade that fuels every war',
    fullDesc: 'Nuclear weapons create an existential paradox: they may have prevented direct great-power war through mutually assured destruction (MAD), but they also create the risk of civilization-ending catastrophe through miscalculation, accident, or escalation. Meanwhile, the conventional arms trade floods conflict zones with weapons — the five permanent UN Security Council members are also the world\'s top five arms exporters. Small arms and light weapons cause the vast majority of conflict deaths.',
    examples: [
      { name: 'North Korea', detail: 'Nuclear arsenal as regime survival insurance, resisting all disarmament' },
      { name: 'Russia-Ukraine', detail: 'Nuclear threats constraining Western response to invasion' },
      { name: 'Taiwan', detail: 'Nuclear deterrence underpins the strategic balance' },
      { name: 'Iran', detail: 'Nuclear program creating regional proliferation fears' },
      { name: 'Global arms trade', detail: 'UN Security Council members sell 76% of global arms exports' },
    ]
  },
  {
    number: '06',
    title: 'Geopolitical Rivalry & Proxy Wars',
    color: '#2ecc71',
    shortDesc: 'When great powers compete for influence, smaller nations become battlefields',
    fullDesc: 'Many conflicts that appear local are actually theaters of great-power competition. During the Cold War, the US and USSR fought through proxies across three continents. Today, US-China competition, the Saudi-Iran rivalry, and Russia\'s attempts to maintain influence create similar dynamics. Proxy involvement makes conflicts harder to resolve because external powers have their own interests that may not align with peace. Foreign arms supplies, funding, and diplomatic backing sustain conflicts that might otherwise reach a tipping point toward negotiation.',
    examples: [
      { name: 'Yemen', detail: 'Saudi-Iran rivalry turned a civil war into a regional conflict' },
      { name: 'Syria', detail: 'Russia, Iran, Turkey, US — each backing different factions' },
      { name: 'Sahel', detail: 'Russia (Wagner) vs. France/West for influence in Africa' },
      { name: 'Sudan', detail: 'UAE backing RSF, Egypt supporting SAF, regional power plays' },
      { name: 'DRC', detail: 'Rwanda\'s backing of M23 for strategic and economic interests' },
    ]
  },
  {
    number: '07',
    title: 'Climate Change & Resource Scarcity',
    color: '#1abc9c',
    shortDesc: 'The threat multiplier — climate change intensifies every existing tension',
    fullDesc: 'Climate change doesn\'t directly cause wars, but it dramatically intensifies existing tensions. Droughts displace farmers, creating competition for shrinking resources. Rising seas threaten island nations and coastal populations. Water scarcity creates interstate tensions (like the Nile dispute). The World Bank estimates 216 million people could be internally displaced by climate by 2050. Climate-driven instability is already visible in the Sahel, Horn of Africa, and Middle East.',
    examples: [
      { name: 'Sahel', detail: 'Desertification driving farmer-herder conflicts and displacement' },
      { name: 'Somalia', detail: 'Repeated droughts creating food insecurity and fueling recruitment' },
      { name: 'Syria', detail: 'Severe drought (2006-2010) contributed to rural-urban displacement before the war' },
      { name: 'Ethiopia/Egypt', detail: 'Nile water dispute intensified by changing rainfall patterns' },
      { name: 'Lake Chad Basin', detail: 'Lake shrunk 90% since 1960s, fueling Boko Haram recruitment' },
    ]
  },
];

// ---- Historical Conflicts ----
const historicalConflicts = [
  {
    date: '1914–1918',
    name: 'World War I',
    desc: 'The "war to end all wars" killed 20 million people. Triggered by a network of alliances, imperial competition, nationalism, and the assassination of Archduke Franz Ferdinand. It demonstrated how interconnected alliance systems could turn a local crisis into a global catastrophe.',
    howEnded: 'Military exhaustion and the 1918 Armistice. The Treaty of Versailles imposed harsh reparations on Germany — creating the grievances that would fuel WWII. The League of Nations was created to prevent future wars but lacked enforcement power.',
    lesson: 'Punitive peace creates future wars. Alliances without communication channels create escalation spirals. International institutions need enforcement power, not just aspirations.',
  },
  {
    date: '1939–1945',
    name: 'World War II',
    desc: 'The deadliest conflict in history: 70-85 million deaths. Arose from WWI\'s unresolved grievances, global economic depression, fascist ideology, expansionism, and the Holocaust. Ended with nuclear weapons — introducing an existential threat to humanity.',
    howEnded: 'Unconditional surrender after total military defeat. Followed by the Marshall Plan (rebuilding former enemies), the United Nations, NATO, and the European integration project. Unlike WWI, victors invested in rebuilding the defeated nations.',
    lesson: 'Invest in rebuilding enemies rather than punishing them. Create strong international institutions. Economic interdependence between former enemies (EU) can make war unthinkable. Never ignore early warning signs of genocide.',
  },
  {
    date: '1947–1991',
    name: 'The Cold War',
    desc: 'A 44-year global confrontation between the US and USSR that never became a direct war — largely because of nuclear deterrence (MAD). Instead, it was fought through proxy wars (Korea, Vietnam, Afghanistan, Angola, Central America), an arms race, space race, and ideological competition.',
    howEnded: 'Internal economic exhaustion of the USSR, democratic movements in Eastern Europe, Gorbachev\'s reforms (glasnost and perestroika), diplomatic engagement (Helsinki Accords, arms control treaties), and ultimately the peaceful dissolution of the Soviet Union in 1991.',
    lesson: 'Deterrence can prevent direct war but doesn\'t prevent suffering (proxy wars killed millions). Diplomacy and arms control save lives. Internal reform and economic pressure can change even the most entrenched systems. Peaceful transitions are possible even from the most dangerous standoffs.',
  },
  {
    date: '1955–1975',
    name: 'Vietnam War',
    desc: 'The US intervened to prevent communist unification of Vietnam, escalating into one of the most destructive wars of the Cold War era. 3.5 million Vietnamese and 58,000 Americans died. Massive bombing campaigns, chemical weapons (Agent Orange), and civilian suffering.',
    howEnded: 'Military stalemate, domestic anti-war movement in the US, Paris Peace Accords (1973), US withdrawal, and North Vietnamese military victory (1975). Vietnam reunified under communist rule but eventually normalized relations with the US and integrated into the global economy.',
    lesson: 'Military force cannot defeat a determined national liberation movement. Domestic public opinion is a critical factor. Former enemies can reconcile — the US and Vietnam are now strategic partners. Ideological wars often end through economic pragmatism.',
  },
  {
    date: '1994',
    name: 'Rwandan Genocide',
    desc: 'In just 100 days, approximately 800,000 Tutsi and moderate Hutu were systematically murdered by Hutu extremists. The international community, including the UN, failed to intervene despite clear warnings. A preventable catastrophe that exposed the hollowness of "never again."',
    howEnded: 'The Rwandan Patriotic Front (RPF) under Paul Kagame militarily defeated the genocidal regime. Afterward, Rwanda established community-based Gacaca courts for transitional justice, abolished ethnic identity cards, and rebuilt with a focus on national unity and economic development.',
    lesson: 'Early warning signs of genocide must be acted upon — the international community had clear intelligence but chose not to intervene. Dehumanizing language and propaganda precede mass violence. Community-based justice can support reconciliation. A society can rebuild even from the worst atrocity.',
  },
  {
    date: '1968–1998',
    name: 'The Troubles (Northern Ireland)',
    desc: 'A 30-year conflict between unionists (mostly Protestant, wanting to remain part of the UK) and nationalists (mostly Catholic, seeking union with Ireland). Over 3,500 people were killed in bombings, shootings, and state violence in a deeply divided society.',
    howEnded: 'The Good Friday Agreement (1998) — a masterwork of compromise. Power-sharing government between unionists and nationalists. North-South institutions linking Northern Ireland and Ireland. Decommissioning of weapons. Prisoner releases. A commitment that Northern Ireland\'s status would be decided by democratic consent of its people.',
    lesson: 'Even the most entrenched identity conflicts can be resolved through creative power-sharing arrangements. All parties must be included in negotiations (including those with violent histories). Compromise means nobody gets everything they want. Economic development and generational change reinforce peace.',
  },
  {
    date: '1948–1994',
    name: 'South African Apartheid',
    desc: 'A system of institutionalized racial segregation and oppression in South Africa, where the white minority ruled over the Black majority through discriminatory laws, forced removals, imprisonment of dissidents, and violence.',
    howEnded: 'A combination of sustained internal resistance (ANC, labor unions, civic movements), international sanctions and boycotts, economic pressure, and visionary leadership from both Nelson Mandela and F.W. de Klerk. The negotiated transition led to the first free elections in 1994 and the Truth and Reconciliation Commission.',
    lesson: 'Sustained nonviolent resistance combined with international pressure can topple even entrenched systems. Truth and reconciliation processes allow societies to acknowledge the past without endless cycles of retribution. Leadership that prioritizes the future over revenge is transformative. Economic sanctions and cultural boycotts matter.',
  },
  {
    date: '1992–1995',
    name: 'Bosnian War',
    desc: 'The breakup of Yugoslavia led to Europe\'s worst violence since WWII. Ethnic cleansing, the siege of Sarajevo, and the Srebrenica massacre (8,000 Bosniak men and boys murdered) exposed the failure of the international community to prevent genocide in Europe.',
    howEnded: 'NATO intervention (airstrikes), US-brokered Dayton Peace Accords (1995) creating a complex power-sharing structure between Bosniaks, Croats, and Serbs. The International Criminal Tribunal for the former Yugoslavia (ICTY) established accountability for war crimes.',
    lesson: 'International intervention must be timely — delayed action costs lives. Post-conflict governance structures must balance ethnic concerns while building shared institutions. International criminal tribunals establish accountability and deter future atrocities. However, Dayton\'s ethnic power-sharing also entrenched divisions — a cautionary tale about freezing identity into governance.',
  },
  {
    date: '1964–2016',
    name: 'Colombian Civil War (FARC)',
    desc: 'A 52-year armed conflict between the Colombian government and FARC guerrillas, also involving paramilitaries and drug cartels. Over 260,000 killed, 7 million displaced. One of the Western Hemisphere\'s longest and most complex conflicts.',
    howEnded: 'The 2016 Peace Agreement, negotiated over 4 years in Havana. It included FARC disarmament, political participation for ex-combatants, transitional justice (Special Jurisdiction for Peace), rural development programs, and drug crop substitution. A referendum initially rejected the deal, but a revised version was passed through Congress.',
    lesson: 'Even 52-year wars can end through negotiation. Comprehensive agreements must address root causes (land, poverty, political exclusion), not just stop the fighting. Transitional justice that balances accountability with peace incentives is essential. Implementation is harder than signing — ongoing commitment is crucial.',
  },
  {
    date: '1950–1953',
    name: 'Korean War',
    desc: 'The first major proxy war of the Cold War. North Korea invaded South Korea, the US/UN intervened, China entered on the North\'s side, and the conflict killed 3-4 million people. It ended in an armistice, not a peace treaty — technically still ongoing.',
    howEnded: 'An armistice agreement in 1953 created the DMZ and froze the conflict. No peace treaty was ever signed. The two Koreas remain divided, with radically different systems. South Korea transformed from a war-ravaged country into a thriving democracy and economic powerhouse.',
    lesson: 'Frozen conflicts can persist for generations. Armistices are not peace — unresolved conflicts can re-escalate at any time. Economic development and democratization don\'t require resolving the underlying conflict, but they create conditions for eventual resolution. Investment in a former war zone (South Korea) can produce remarkable transformation.',
  },
];

// ---- How Wars End ----
const howWarsEnd = [
  {
    icon: '🤝',
    title: 'Negotiated Settlement',
    color: '#2ecc71',
    desc: 'The most durable path to peace. Both sides agree to compromise through structured talks, often with international mediation. Research shows negotiated settlements, when properly implemented, last longer than military victories.',
    examples: ['Good Friday Agreement (Northern Ireland)', 'Colombia-FARC Peace Deal (2016)', 'Dayton Accords (Bosnia)', 'Mozambique Peace Agreement (1992)'],
    successRate: 65,
    successColor: '#2ecc71',
  },
  {
    icon: '🏛️',
    title: 'International Mediation & Institutions',
    color: '#3498db',
    desc: 'Third-party mediators — the UN, regional organizations, or trusted nations — provide neutral ground, build confidence, and help parties find solutions they couldn\'t reach alone. International peacekeeping reduces recurrence of violence by 50%.',
    examples: ['Camp David Accords (Egypt-Israel, 1978)', 'Pretoria Agreement (Ethiopia-Tigray, 2022)', 'UN mediation in El Salvador (1992)', 'ASEAN in Cambodia (1991)'],
    successRate: 55,
    successColor: '#3498db',
  },
  {
    icon: '💰',
    title: 'Economic Interdependence',
    color: '#1abc9c',
    desc: 'Making war too economically costly. The European Union was explicitly designed to make war between France and Germany impossible by binding their economies together. Trade creates shared interests that make conflict irrational.',
    examples: ['European Coal and Steel Community → EU', 'US-Japan post-WWII economic partnership', 'ASEAN economic integration', 'China-Taiwan economic ties (stabilizing factor)'],
    successRate: 75,
    successColor: '#1abc9c',
  },
  {
    icon: '⚖️',
    title: 'Truth, Justice & Reconciliation',
    color: '#9b59b6',
    desc: 'Addressing the past without endless cycles of revenge. Truth commissions, war crimes tribunals, and community-based justice help societies acknowledge what happened, hold perpetrators accountable, and build a foundation for coexistence.',
    examples: ['South Africa\'s TRC (1996)', 'Rwanda\'s Gacaca courts', 'Colombia\'s Special Jurisdiction for Peace', 'ICTY for the former Yugoslavia'],
    successRate: 60,
    successColor: '#9b59b6',
  },
  {
    icon: '🏗️',
    title: 'Post-Conflict Reconstruction',
    color: '#e67e22',
    desc: 'Investing in rebuilding destroyed societies — infrastructure, institutions, education, health. The Marshall Plan after WWII demonstrated that generous reconstruction of former enemies creates lasting peace and prosperous allies.',
    examples: ['Marshall Plan (Europe, 1948-1952)', 'Japan\'s post-WWII reconstruction', 'Rwanda\'s remarkable recovery', 'South Korea\'s transformation'],
    successRate: 70,
    successColor: '#e67e22',
  },
  {
    icon: '🔄',
    title: 'Power-Sharing Arrangements',
    color: '#f1c40f',
    desc: 'When divided societies can\'t agree on who governs, structured power-sharing ensures all major groups have a voice. This can break zero-sum politics where one group\'s win is another\'s loss.',
    examples: ['Northern Ireland Assembly', 'Lebanon\'s confessional system', 'Burundi\'s ethnic quotas', 'Bosnia\'s rotating presidency'],
    successRate: 50,
    successColor: '#f1c40f',
  },
];

// ---- Patterns ----
const patterns = [
  {
    icon: '📊',
    title: 'Wars Are Getting Fewer But Deadlier',
    content: 'Interstate wars between countries have declined dramatically since 1945 — the UN system, nuclear deterrence, and economic interdependence work. But civil wars and internal conflicts have increased, often lasting decades. Modern conflicts kill more civilians through indirect causes (famine, disease, displacement) than direct combat.',
    points: [
      'Interstate wars have declined by over 70% since 1945',
      'Civil wars last an average of 10+ years, up from 2 years in the 1950s',
      '90% of conflict deaths are now civilians, up from 10% in WWI',
      'Indirect deaths (hunger, disease) often exceed combat deaths by 5:1',
    ]
  },
  {
    icon: '🔁',
    title: 'Conflicts Recur Without Root-Cause Solutions',
    content: 'About 60% of civil wars restart within a decade of ending. Wars that end through negotiation without addressing underlying causes — poverty, exclusion, grievance — almost always reignite. Military victory alone rarely produces lasting peace.',
    points: [
      '60% of civil wars restart within 10 years',
      'Wars ended by military victory recur 50% of the time',
      'Negotiated settlements with implementation support recur only 20-30% of the time',
      'Addressing root causes (governance, economy, inclusion) is the key variable',
    ]
  },
  {
    icon: '🌐',
    title: 'External Involvement Prolongs Conflicts',
    content: 'When outside powers provide weapons, funding, or political support to warring parties, conflicts last significantly longer. Proxy wars are harder to resolve because external actors have their own interests that may not align with local peace.',
    points: [
      'Conflicts with significant external involvement last 3x longer on average',
      'Arms transfers to conflict zones correlate with conflict duration',
      'The 5 permanent UN Security Council members are the top 5 arms exporters',
      'When external powers align on peace (as in Mozambique), resolution accelerates',
    ]
  },
  {
    icon: '📈',
    title: 'Democracy and Development Reduce Conflict Risk',
    content: 'No two established democracies have ever gone to war with each other (the "Democratic Peace" theory). Countries with higher GDP per capita, lower inequality, and stronger rule of law are dramatically less likely to experience civil war.',
    points: [
      'Established democracies have never fought each other',
      'Doubling GDP per capita halves civil war risk',
      'Countries in the "anocracy" zone (semi-democratic) are most conflict-prone',
      'Education, especially for girls, is one of the strongest peace predictors',
    ],
    fullWidth: true,
  },
  {
    icon: '⚠️',
    title: 'Warning Signs Are Predictable',
    content: 'Genocides and mass atrocities are never spontaneous. They follow predictable patterns: dehumanizing language, scapegoating, political polarization, militia formation, and weapons stockpiling. Early intervention at these stages is far cheaper and more effective than responding after violence begins.',
    points: [
      'Dehumanizing language in media and politics precedes violence by months to years',
      'Economic shocks combined with identity polarization create the highest risk',
      'The international community had clear warnings before Rwanda, Bosnia, and Myanmar',
      'Prevention costs 1/60th of military intervention after conflict begins',
    ]
  },
  {
    icon: '✨',
    title: 'Peace Is the Norm, Not the Exception',
    content: 'Despite constant news coverage of conflict, the vast majority of the world is at peace. Most diverse societies manage their differences without violence. The global trajectory over centuries is toward less violence — but progress requires constant effort and is never guaranteed.',
    points: [
      'Steven Pinker\'s data shows per-capita violence has declined over centuries',
      'Most countries that could be at war with neighbors are not',
      'International trade, institutions, and norms constrain conflict behavior',
      'Every generation must actively choose and build peace — it is not automatic',
    ]
  },
];

// ---- Path Forward ----
const pathForward = [
  {
    step: 'Foundation 01',
    title: 'Strengthen International Institutions',
    desc: 'Reform and empower the institutions designed to prevent war. The UN Security Council veto system, designed in 1945, paralyzes response to modern conflicts. Regional organizations need more capacity. International law needs enforcement.',
    actions: [
      'Reform the UN Security Council to limit veto power on mass atrocity situations',
      'Strengthen the International Criminal Court with universal jurisdiction',
      'Empower regional organizations (AU, ASEAN, EU) with rapid response capabilities',
      'Create binding mechanisms for arms trade regulation and enforcement',
    ],
  },
  {
    step: 'Foundation 02',
    title: 'Invest in Prevention, Not Just Response',
    desc: 'For every $1 spent on conflict prevention, we save $16 in crisis response. Yet the vast majority of international spending goes to military response and humanitarian relief rather than addressing root causes before violence begins.',
    actions: [
      'Fund early warning systems and rapid diplomatic response mechanisms',
      'Invest in governance, education, and economic development in fragile states',
      'Address climate change as a security priority, not just an environmental one',
      'Support local peace infrastructure — community mediators, civil society, local governance',
    ],
  },
  {
    step: 'Foundation 03',
    title: 'End the Arms Trade to Conflict Zones',
    desc: 'You cannot put out a fire while pouring gasoline on it. The global arms trade — worth $100+ billion annually — directly fuels every conflict on this page. The countries calling for peace are often the same ones selling weapons to warring parties.',
    actions: [
      'Enforce and strengthen the Arms Trade Treaty',
      'End arms sales to countries committing human rights violations',
      'Implement conflict mineral regulations globally (like the EU model)',
      'Increase transparency in military spending and arms deals',
    ],
  },
  {
    step: 'Foundation 04',
    title: 'Build Economic Interdependence',
    desc: 'The European Union\'s founding insight remains the most powerful peace strategy ever devised: make neighboring economies so intertwined that war becomes economically irrational. Trade, investment, and shared infrastructure create peace.',
    actions: [
      'Support regional economic integration in conflict-prone areas',
      'Invest in cross-border infrastructure and trade',
      'Create economic incentives for peace and costs for aggression (smart sanctions)',
      'Ensure economic development is inclusive and reduces inequality',
    ],
  },
  {
    step: 'Foundation 05',
    title: 'Promote Inclusive Governance',
    desc: 'The evidence is overwhelming: inclusive governance that gives all groups a voice dramatically reduces conflict risk. This means democracy, rule of law, minority protections, free media, and accountability. Authoritarianism is a conflict factory.',
    actions: [
      'Support democratic transitions and elections with integrity',
      'Protect minority rights and ensure political inclusion',
      'Strengthen independent media and counter disinformation',
      'Build institutions that survive individual leaders — rule of law, not rule of strongmen',
    ],
  },
  {
    step: 'Foundation 06',
    title: 'Educate for Peace',
    desc: 'Peace is not naive — it is the most sophisticated and evidence-based approach to security. Education that teaches critical thinking, empathy, historical context, and conflict resolution skills creates generations who refuse to be manipulated into violence.',
    actions: [
      'Integrate peace education and conflict resolution into school curricula globally',
      'Teach media literacy to counter propaganda and dehumanization',
      'Support exchange programs that build cross-cultural understanding',
      'Fund research on conflict prevention, resolution, and peacebuilding',
    ],
  },
];

// ---- Applying History to Today ----
const applyLessons = [
  {
    current: 'Russia–Ukraine War',
    historical: 'Cold War & Post-WWII Europe',
    lesson: 'The Cold War ended through a combination of deterrence, diplomacy, and internal change — not military victory. The post-WWII settlement succeeded because victors invested in rebuilding (Marshall Plan) and created economic interdependence (EU). A sustainable resolution must include security guarantees, economic reconstruction, and a new European security architecture — not punitive terms that create future grievances (the lesson of Versailles).',
  },
  {
    current: 'Israel–Palestine Conflict',
    historical: 'Northern Ireland (Good Friday Agreement)',
    lesson: 'Northern Ireland shows that even the most entrenched identity conflicts — where both sides have legitimate grievances and claims — can be resolved through creative power-sharing, acknowledging both narratives, and a framework that doesn\'t require either side to surrender their identity. It required including former combatants in negotiations, addressing prisoner issues, and building a "parity of esteem" between communities. All-or-nothing approaches failed; creative compromise succeeded.',
  },
  {
    current: 'Sudan Civil War',
    historical: 'South Africa\'s Democratic Transition',
    lesson: 'South Africa demonstrated that even deeply entrenched power structures can be transformed through a combination of internal resistance, international pressure (sanctions), and negotiated transition. The key was leadership willing to prioritize the future over retribution, and a truth and reconciliation process that acknowledged the past. Sudan\'s civilian pro-democracy movement needs international support and a framework that integrates, rather than sidelines, civilian voices.',
  },
  {
    current: 'Myanmar Civil War',
    historical: 'South Africa & Indonesia\'s Democratic Transition',
    lesson: 'Indonesia\'s transition from the Suharto military dictatorship (1998) showed that even entrenched military regimes can fall when they lose economic legitimacy and face unified resistance. South Africa showed that targeted sanctions and diplomatic isolation can accelerate change. Myanmar\'s resistance needs sustained international pressure, sanctions on military revenue sources (oil, gas, gems), and recognition of the democratic government.',
  },
  {
    current: 'DR Congo (Eastern Conflict)',
    historical: 'Sierra Leone & Blood Diamonds',
    lesson: 'The Sierra Leone civil war (1991-2002) was similarly fueled by resource extraction (diamonds). The Kimberley Process for conflict diamonds — while imperfect — showed that international supply chain regulation can reduce the economic incentive for armed groups. Applying similar frameworks to coltan, cobalt, and gold in Congo, combined with serious diplomatic pressure on Rwanda, is essential.',
  },
  {
    current: 'Sahel Crisis',
    historical: 'Colombia & Counterinsurgency',
    lesson: 'Colombia spent decades trying to defeat FARC militarily before recognizing that root causes — rural poverty, political exclusion, lack of services — fueled recruitment. The 2016 peace deal addressed these through rural development, political participation, and drug crop substitution. The Sahel\'s jihadist insurgencies are similarly fueled by governance failure and marginalization, not just ideology. Military force alone will fail.',
  },
];

// ---- What You Can Do (Actions) ----
const takeActions = [
  {
    icon: '📚',
    title: 'Educate Yourself & Others',
    color: '#3498db',
    urgency: 'Start today',
    desc: 'Knowledge is the foundation of change. Understanding why conflicts happen — and how they end — gives you the power to see through propaganda, reject manipulation, and advocate for evidence-based solutions.',
    actions: [
      'Read this entire resource — understand the patterns, not just the headlines',
      'Follow independent, fact-based conflict reporting (ACLED, ICG, OCHA)',
      'Learn about the history of successful peace processes — not just wars',
      'Share what you learn with family, friends, and colleagues',
      'Organize discussion groups in your school, university, or community',
      'Question media narratives: ask "who benefits?" and "what\'s the root cause?"',
    ]
  },
  {
    icon: '📣',
    title: 'Demand Action From Your Leaders',
    color: '#e74c3c',
    urgency: 'Most impactful',
    desc: 'Politicians respond to pressure. Every major peace breakthrough in history — from the anti-apartheid movement to the Nuclear Test Ban Treaty — happened because citizens demanded it. Your voice matters more than you think.',
    actions: [
      'Write to your elected representatives about specific conflicts — name them',
      'Ask candidates their position on arms exports, conflict prevention, and diplomacy',
      'Demand transparency in your country\'s arms sales and military spending',
      'Support legislation for conflict mineral due diligence in supply chains',
      'Push for increased funding for diplomacy and prevention (not just military)',
      'Vote for leaders who prioritize international cooperation and peace',
    ]
  },
  {
    icon: '🤝',
    title: 'Support Peace Organizations',
    color: '#2ecc71',
    urgency: 'Immediate impact',
    desc: 'Organizations on the ground are doing critical peacebuilding work — often with minimal funding. Your support directly enables conflict resolution, humanitarian aid, and human rights documentation.',
    actions: [
      'Donate to humanitarian organizations (ICRC, MSF, UNHCR) providing relief',
      'Support conflict resolution organizations (International Crisis Group, Search for Common Ground)',
      'Back human rights documentation (Human Rights Watch, Amnesty International)',
      'Fund local peace organizations in conflict-affected areas',
      'Support investigative journalism that exposes the truth about conflicts',
      'Volunteer your skills — translation, tech, research, advocacy',
    ]
  },
  {
    icon: '🛒',
    title: 'Use Your Economic Power',
    color: '#e67e22',
    urgency: 'Everyday action',
    desc: 'Every purchase is a vote. Conflicts are fueled by economic systems — minerals in your phone, oil in your car, investments in arms companies. Consumer and investor pressure has ended apartheid and changed corporate behavior.',
    actions: [
      'Buy conflict-free electronics — demand supply chain transparency from tech companies',
      'Divest from arms manufacturers and companies profiting from conflict',
      'Support fair trade products from conflict-affected regions',
      'Choose companies with ethical sourcing and human rights policies',
      'Support economic sanctions campaigns against aggressive regimes',
      'Invest in ESG funds that exclude arms and conflict-linked industries',
    ]
  },
  {
    icon: '💬',
    title: 'Build Bridges, Not Walls',
    color: '#9b59b6',
    urgency: 'Daily practice',
    desc: 'Wars start with dehumanization — the belief that "they" are different, lesser, or threatening. Every time you build understanding across differences, you make conflict harder to start and sustain.',
    actions: [
      'Engage respectfully with people who hold different views — model dialogue',
      'Reject and call out dehumanizing language about any group',
      'Learn about cultures, histories, and perspectives different from your own',
      'Support refugee and immigrant communities in your area',
      'Push back against propaganda and disinformation in your social circles',
      'Teach your children empathy, critical thinking, and conflict resolution',
    ]
  },
  {
    icon: '🏫',
    title: 'For Educators & Schools',
    color: '#1abc9c',
    urgency: 'Shape the future',
    desc: 'Teachers shape how the next generation understands conflict and peace. Integrating these topics into education creates citizens who are informed, empathetic, and resistant to manipulation.',
    actions: [
      'Use this resource as a teaching tool — it\'s free and designed for education',
      'Teach conflict analysis: root causes, actors, interests, and solutions',
      'Include peace studies alongside war history — how conflicts ended, not just how they were fought',
      'Develop media literacy programs — teach students to evaluate sources critically',
      'Organize Model UN, debate clubs, or peace simulations',
      'Invite speakers from conflict-affected communities and peacebuilding organizations',
    ]
  },
];
